### ISSUE TITLE
Duration property isn't respected for VelocityTransitionGroup and UI pack animations

### ISSUE THREAD

**Issue by SpadarShut** [twitter-fabric/velocity-react#104]
```
<VelocityTransitionGroup duration={250} enter={{ animation: 'transition.expandIn' }} leave={{ animation: 'transition.fadeOut' }}>
{this.getActiveStep()}
</VelocityTransitionGroup>
```
In the code above the transitions run about 1s no matter what duration is set. When the animation key is changed to simple 'fadeIn' then duration works as expected.

**Comment by finneganh** [comment]
`duration` needs to be set for `enter` and `leave` separately. Put them in the hashes alongside `animation`.
