### ISSUE TITLE
is there a componentWillEnter or componentDidEnter?

### ISSUE THREAD

**Issue by abellee** [twitter-fabric/velocity-react#107]
I used this lib to control the transition effect of the react-router.
and I have some requests when the componentDidMount was triggered.
but if I do request in componentDidMount, the request will cause the transition effect not so smoothly.
So I wanna know if I could do something in like componentDidEnter, it will be better, right?

**Comment by finneganh** [comment]
I think you'll need to investigate what isn't smooth about the current effect. There a lot of processing going on when the routes change, or just components resizing when they get new data and that throwing off the animation.

I believe you could add a `complete` callback to the `VelocityTransitionGroup`'s `enter` or `leave` animations that will get called when the effect is done. That may help, though there might be some bookkeeping to translate that to a specific component.
