### ISSUE TITLE
Cannot easily run a sequence loop

### ISSUE THREAD

**Issue by iSimonWeb** [twitter-fabric/velocity-react#111]
Hey there, this is awesome, no other library can outstand Velocity in matter of performance.
Using it with react anyway is a little bit tricky and I've just found impossible to loop a sequence of animations, because the only way to make a sequence is using VelocityUI with registerEffect that, unfortunately, does not support looping.

Is there a way to use the "native" method `runSequence()`?
Thank you so much.

**Comment by finneganh** [comment]
Would it work for you to include a `complete` callback and then call the `runAnimation` method on the component manually to cause a loop?

Does `RunSequence` have support for looping in a way that's different from calling `$.velocity`?

**Comment by ShakurOo** [comment]
Hello,

I trying to doing this, i can catch the callback complete but i don't know how i can show runAnimation().
May I can inject as parameters the name of the animation ?

**Comment by jwdinker** [comment]
Wanted to get your guys thoughts on something like this.  I have read mixed feedback on using setTimeout for animations, but I haven't found a viable work around for running animation sequences in React-Velocity. The rough solution I have come up with so far works so far and looks something like this...

1.  Pass in array of object animations and include the the delay and duration.
2.  A timeout is created for each animation sequence that factors in the delay of the next animation and the duration of the current animation.   


`
export class VelocityAnimationSequence extends Component {

    constructor (props) {
         super(props)
    }


    static defaultProps = {
        sequences:[
         {animation: {height:'100px'},delay:200, duration:200},
         {animation: {opacity:1}, duration:2000},
         {animation: {opacity:0}, duration:500},
         {animation: {height:'0px'},duration:1000}
        ],
        on_sequence_end:()=>{console.log("The sequence has ended")}
    }


   state = {
       current_sequence:0,
       animation_timeout_id:null,
   }

   //
    next_sequence () {
        clearTimeout(this.state.animation_timeout_id)
        if(this.state.current_sequence < this.props.sequences.length - 2){
            this.setState({current_sequence:this.state.current_sequence + 1, animation_timeout_id:this.create_sequence_timeout(this.get_duration_plus_delay(this.state.current_sequence + 1, this.state.current_sequence + 2))})
        }else if(this.state.current_sequence < this.props.sequences.length - 1){
            this.setState({current_sequence:this.state.current_sequence + 1, animation_timeout_id:this.create_sequence_timeout(this.get_duration_plus_delay(this.state.current_sequence + 1, this.state.current_sequence + 1))})
        }else{
            this.props.on_sequence_end()
            clearTimeout(this.state.animation_timeout_id)
        }

    }


    get_duration_plus_delay(duration_index, delay_index){
        return this.props.sequences[duration_index].duration + this.delay_check(this.props.sequences[delay_index].delay)
    }

    delay_check(delay){
        return (typeof delay === 'undefined') ? 0 : delay
    }

    //add plus delay?
    create_sequence_timeout (duration) {
        setTimeout(()=>{
            this.next_sequence()
        }, duration)
    }


    
    //on first mount, the first duration and delay are added together along with the delay from the second sequence.
    componentWillMount () {
        this.setState({animation_timeout_id:this.create_sequence_timeout(this.get_duration_plus_delay(0,1))})
    }

    render () {
        console.log('current_sequence', this.state.current_sequence, '\n current_duration', this.props.sequences[this.state.current_sequence].duration)

        var {animation, display, duration, delay} = this.props.sequences[this.state.current_sequence]
        
        return (
           <VelocityComponent 
                animation={animation} 
                runOnMount={true} 
                display={display}
                delay={(this.state.current_sequence === 0) ? delay : 'undefined'}
                duration={duration}>
            {this.props.children}
           </VelocityComponent>
        )

        

    }

}



`
