### ISSUE TITLE
Prevent expand and collapse immediately

### ISSUE THREAD

**Issue by slashtu** [twitter-fabric/velocity-react#117]
If I render content quickly, like click button very fast. The content will expand and collapse immediately. Is there any attribute can prevent this action ? Now I need to use a flag to prevent render e.g. 

```
let inProcess = false;
const processTime = 500;

toggle: function(){

    if( inProcess ) return;
    inProcess = true;

    setTimeout( () => { inProcess = false; }, processTime);

   // render content
}
```

**Comment by finneganh** [comment]
Are you using `VelocityComponent` or `VelocityTransitionGroup`?
