### ISSUE TITLE
updating styles in progress callback

### ISSUE THREAD

**Issue by angus-c** [twitter-fabric/velocity-react#124]
Here's my use case:
```
<VelocityComponent>
  <MyComponent/>
</VelocityComponent>
```
For each animation loop, MyComponent's `width` should start at 10, grow to 20 at the half way point, then ease back to 10. I don't think I can use the animation property for this (since start and end values are 10).

The progress property supplies the `complete` value to the associated callback, which I could potentially use to update width via something like: 
```
progress={(el, complete) => {width: 20 - (Math.abs(complete - 0.5)*20)}}
``` 
However I'm not sure how (or whether) I can update a style property via this callback (or if there's any other way to achieve this goal)

**Comment by finneganh** [comment]
You should be able to use the VelocityHelper to register a multi-step
animation that goes to 20 and then back to 10.

**Comment by angus-c** [comment]
Thanks! I got something sort of working, but having several issues:

```
    this.widthEffect = velocityHelpers.registerEffect({
      calls: [
        [{width: '20px', left: 125}],
        [{width: '10px', left: 250}],
      ],
    });
```

1) it treats each section (i.e. element in the call array) as a separate easing. So instead of one spring, there's a spring followed by another spring
2) the width starts from 100% unless I set it to '10px' in the css, after which it stays at 10px
3) I can't make it loop 

Unfortunately I can't find much to help me in the regular velocity documentation for this topic: http://velocityjs.org/#uiPack

**Comment by finneganh** [comment]
You should be able to modify the easing w/ additional arguments. Unfortunately the `registerEffect` bits are not well-documented in Velocity. You can also set the initial width I think with:

`
[{
  width: [20, 10],
  left: …
}, …]
`

I believe that you cannot loop `registerEffect` animations, but you could add a `complete` handler to the component and have that call `runAnimation`.
