### ISSUE TITLE
deprecated react usage

### ISSUE THREAD

**Issue by FridaCai** [twitter-fabric/velocity-react#125]
Hi, i am using react component tree-beard and got this warning message about velocity.

warning.js:36 Warning: You are manually calling a React.PropTypes validation function for the `runOnMount` prop on `VelocityTransitionGroup`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by finneganh** [comment]
This seems to be an NPM / Treebeard issue. Treebeard's dev dependencies specify React 0.14.8, but the NPM I have (2.7.5) is installing a React for velocity-react's peerDependency, even though 0.14.8 should satisfy the ||.

In your own app, lock React down at 15.something and I expect you won't have warnings.

I'm not sure if npm 3 would handle this case better.
