### ISSUE TITLE
VelocityTransitionGroup multiple components leaving raises error

### ISSUE THREAD

**Issue by matthewjf** [twitter-fabric/velocity-react#142]
Using VelocityTransitionGroup, an errors occurs when multiple components leave at the same time. 

`Uncaught TypeError: Cannot read property 'componentDidLeave' of undefined`

It happens when multiple subcomponents are removed and it happens once for each subcomponent that's removed after the first. When I tried a stagger, it seemed like all of the subcomponents were removed at the same time. Staggering the enter animation didn't have the same issue.

Packages

```
  react@15.3.2
  react-dom@15.3.2 
  velocity-animate@1.3.1 
  velocity-react@1.1.11 
```

Basic component

```
import React from 'react';
import {VelocityTransitionGroup} from 'velocity-react';

var enterAnimation = {
  animation: 'slideDown',
  stagger: '500ms',
  duration: '500ms',
  style: { display: 'none' }
};

var leaveAnimation = {
  animation: 'slideUp',
  duration: '500ms'
};

class Test extends React.Component {
  constructor(props) {
    super(props);
    this.renderItems = this.renderItems.bind(this);
    this.addFiveItems = this.addFiveItems.bind(this);
    this.removeFiveItems = this.removeFiveItems.bind(this);

    this.state = { counter: 0, items: [] };
  }

  addFiveItems() {
    var counter = this.state.counter;
    var items = this.state.items;
    var i = 5;
    while(i--) {
      counter++;
      items.push(counter);
    }
    this.setState({counter: counter, items: items});
  }

  removeFiveItems() {
    this.setState({items: this.state.items.slice(5)});
  }

  renderItems() {
    return this.state.items.map(item => {
      return <div key={item}>{`item: ${item}`}</div>;
    });
  }

  render() {
    return(
          <div>
            <a onClick={this.addFiveItems}>add 5 items</a>
            <a onClick={this.removeFiveItems}>remove 5 items</a>
            <VelocityTransitionGroup enter={enterAnimation} leave={leaveAnimation}>
              {this.renderItems()}
            </VelocityTransitionGroup>
          </div>
    );
  }
};

export default Test;

```

**Comment by matthewjf** [comment]
Just found https://github.com/twitter-fabric/velocity-react/issues/109, but it doesn't look like it was ever resolved. I'll keep digging around but It would be great if someone with a better understanding could take another look at it.

**Comment by matthewjf** [comment]
After digging around a bit, velocity fires the `complete` callback at the end of each element's animation. It's removing all of the elements at the end of the first element's animation. I'm not entirely sure if this is a bug with velocity.

**Comment by finneganh** [comment]
Aha, interesting. Good find. I can probably figure out how to work around that in how `VelocityTransitionGroup` generates its `complete` function.

**Comment by matthewjf** [comment]
The issue is fixed with velocity
https://github.com/julianshapiro/velocity/commit/48a4e1eb0610a9582448421c684d8a2cbcec5a90

Feel free to close

**Comment by with0out** [comment]
Would be nice to bump the velocity-animate's version, having multiple tables hide&display triggering this same problem, upgrade to velocity-animate@1.4.0 solves this issue.
