### ISSUE TITLE
Is it possible to lazy-load VelocityReact?

### ISSUE THREAD

**Issue by axelson** [twitter-fabric/velocity-react#143]
Since VelocityReact/velocity are quite heavy-weight dependencies it would be nice to lazily load them so that the initial render doesn't need VelocityReact. I'm guessing this would require some sort of initial passthrough components that would just render the underlying components that are later replaced by the full VelocityReact components that are animation enabled.

**Comment by finneganh** [comment]
Yeah, you'd need to do something tricky to handle the class coming in later, which would be dependent upon whatever you're using to do lazy loading.
