### ISSUE TITLE
Static animation every value update?

### ISSUE THREAD

**Issue by mystrdat** [twitter-fabric/velocity-react#146]
How does this wrapper address a usecase where I need to run a single static animation from start to finish every time a value is incremented?

**Comment by finneganh** [comment]
See the "On Demand" section of the demo. You'll want to call `runAnimation` on the component after you detect the increment. See the "Interruption Behavior" options for ways to handle when the animation calls overlap.

**Comment by mystrdat** [comment]
@finneganh Must have missed that feature going through the docs, thank you very much.
