### ISSUE TITLE
Slow animation compare to the stock velocity

### ISSUE THREAD

**Issue by geohuz** [twitter-fabric/velocity-react#148]
Sorry I'm a newbie to the velocity. I'm trying to migrate an animation effect to velocity-react, but it looks like my react rendering is a bit slow, the original velocity code is: 

`var circle = $(".circle");
// The 'animated' bool serves as a toggle \\
var animated = false;

// Animate button size and color with MD standard easing \\
circle.on("click", function() {
  if (!animated) {
    circle.velocity({
      "width": "965px",
      "height": "965px",
      backgroundColor: "#03A9F4"
    }, 250, [0.4, 0.0, 0.2, 1]);
 // Animate top and left properties with different easings \\
 // to create an arc-like movement path                    \\
    circle.velocity({
      "top": "50%"
    },{
      duration: 250,
      easing: "easeInSine",
      queue: false
    });
    circle.velocity({
      "left": "50%"
    },{
      duration: 250,
      easing: "easeOutSine",
      queue: false
    });
    
 // Toggle the animated bool to active the return animation \\
 // on the next click                                       \\
    animated = !animated;
  } else {
    circle.velocity({
      "width": "100px",
      "height": "100px",
      backgroundColor: "#8BC34A"
    }, 250, [0.4, 0.0, 0.2, 1]);
    circle.velocity({
      "top": "80%"
    },{
      duration: 250,
      easing: "easeOutSine",
      queue: false
    });
    circle.velocity({
      "left": "80%"
    },{
      duration: 250,
      easing: "easeInSine",
      queue: false
    });
    animated = !animated;
  }
})`

the react-velocity is: 
`import React from 'react'
import 'velocity-animate'
import 'velocity-animate/velocity.ui'
import { VelocityComponent, velocityHelpers } from 'velocity-react' 
import './App.css'

// note about velocity parts: p: properties, o: option
var FabToMenuMotion = {
  F2M_Reveal: velocityHelpers.registerEffect({
    calls: [
      [{
        width: "965px",
        height: "965px",
        backgroundColor: "#03A9F4"
       }, {easing: [0.4, 0.0, 0.2, 1]}],
      [{top: '50%'}, {easing: "easeInSine", queue: false}],
      [{left: '50%'}, {easing: "easeOutSine", queue: false}]
    ]
  }),
  F2M_Back: velocityHelpers.registerEffect({
    calls: [
      [{
        "width": "100px",
        "height": "100px",
        backgroundColor: "#8BC34A"
      }, [0.4, 0.0, 0.2, 1]],
      [{"top": "80%"}, {easing: "easeOutSine", queue: true}],
      [{"left": "80%"}, {easing: "easeInSine", queue: true}]
    ]
  })
}

var App = React.createClass({
  getInitialState() {
    return { animated: false }
  },
  render: function() {
    return (
      <div>
        <button onClick={()=>this.setState({animated: !this.state.animated})}>
          Toggle
        </button>
        <div className='container'>
          <VelocityComponent 
            animation={this.state.animated? FabToMenuMotion.F2M_Reveal: FabToMenuMotion.F2M_Back}>
              <div className='circle'></div>
          </VelocityComponent>
        </div>
      </div>
    );
  }
});

export default App;`

the css: 

`.container {
  height: 400px;
  width: 800px;
  margin-left: auto;
  margin-right: auto;
  background-color: white;
  /*  These overflow and position properties are necessary for */
  /*  correct clipping behaviour                               */
  overflow: hidden;
  position: relative;
  border-radius: 0px;
}

.circle {
  border-radius: 50%;
  background-color: #8BC34A;
  height: 100px;
  width: 100px;
  position: absolute;
  top: 80%; 
  left: 80%;
  box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
  /*  This transform means that the top and left properties    */
  /*  effectively place the button center instead of the       */
  /*  top-left corner                                          */
  transform: translate(-50%, -50%);
}`

anybody can help me out?

Thanks

**Comment by finneganh** [comment]
I'd recommend not doing the queue stuff but instead change all the properties in one call. There is a somewhat undocumented way you can specify per-property easing with `registerEffect`, which you can see an example of here: https://github.com/julianshapiro/velocity/blob/master/velocity.ui.js#L541
