### ISSUE TITLE
Failed prop type: Invalid prop `runOnMount` of type `string` supplied to `VelocityTransitionGroup`, expected `boolean`.

### ISSUE THREAD

**Issue by jinxin479** [twitter-fabric/velocity-react#150]
## this is my codes
`<VelocityTransitionGroup ref='container' component='div' enter={enterAnimation} leave={leaveAnimation} runOnMount='true' className='container'>
              <Table />        
 </VelocityTransitionGroup>
`
howover, ## the console occur 'Failed prop type: Invalid prop `runOnMount` of type `string` supplied to `VelocityTransitionGroup`, expected `boolean`.

**Comment by finneganh** [comment]
You need `runOnMount={true}`

**Comment by jinxin479** [comment]
thank you
