### ISSUE TITLE
Unable to use example

### ISSUE THREAD

**Issue by Orbyt** [twitter-fabric/velocity-react#155]
Trying out the basic example, but the following in printed to the console:

> A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object

The code im using:

```
import VelocityComponent from 'velocity-animate'
...
<VelocityComponent animation={{ opacity: this.state.opened ? 1 : 0 }} duration={500}>
	{this.state.opened ? <img key={1} src="/times.svg"/> : <img key={2} src="/message.svg"/>}
</VelocityComponent>
```

Im simply trying to animate the transition between the two svgs.

**Comment by finneganh** [comment]
The first line should be:

```
import { VelocityComponent } from 'velocity-animate';
```
