### ISSUE TITLE
Stop the animation at certain point

### ISSUE THREAD

**Issue by jordyvanraaij** [twitter-fabric/velocity-react#156]
In the Velocity documentation (http://velocityjs.org/#stop) they mention a command to stop animations at a certain point. Is this also possible with Velocity-react? I tried multiple ways of implementing it by using the standard Velocity documentation but it didn't work, eg:

```
<VelocityComponent animation={sunAnimation} runOnMount={true} stop={stopAnimation()}>
   <img className={styles.sun} src={sun} alt="Sun" />
</VelocityComponent>
```

**Comment by finneganh** [comment]
`velocity-react` doesn’t expose a way to do "stop" directly. Animations are stopped implicitly by changing the `animation` property. You could also try to expose "stop" the way that `runAnimation` is from `VelocityComponent` instances.
