### ISSUE TITLE
Unable to animate a component that is unmounting

### ISSUE THREAD

**Issue by skurger** [twitter-fabric/velocity-react#161]
Is there an easy way to run animations when unmounting a component similar to supplying the "runOnMount" prop?  I did not see a "runOnUnmount".  I have enter and leave hooks working on other components where a higher order component is controlling the rendering but I'd like to be able to specify how a component animates both in and out in the component definition.   Here is some example code of what I'm trying to do.  I would like these "Tags" to expand in when created and shrink out when they are removed.  Is this possible?

```
const Tag = (props) => {
	return (
		<VelocityTransitionGroup display="inline-block"
			runOnMount={ true }
			runOnUnmount={ true }
			enter={ { animation: "transition.expandIn", duration: 200, display: "inline-block" } }
			leave={ { animation: "transition.expandOut", duration: 200, display: "inline-block" } }>
			<div className='tag'>
				<div className='tag__value'>
					{ props.children }
				</div>
				&nbsp;
				<div
					className='tag__destroy'
					onClick={ props.onDestroyClick }>
					<span className='tag__destroy__icon'>&#215;</span>
				</div>
			</div>
		</VelocityTransitionGroup>
	);
}
```

**Comment by finneganh** [comment]
`VelocityTransitionGroup` will run its animation when its child unmounts. I suspect you just need to rearrange things so that your `VelocityTransitionGroup` is sticking around, and its children are the only ones entering / leaving.
