### ISSUE TITLE
Question, velocity-react and various webpack SVG loaders.

### ISSUE THREAD

**Issue by saniko** [twitter-fabric/velocity-react#162]
Hi,

With regards to SVG and SVG animations.

Any thoughts, known issues or recommendations regarding the following SVG loaders:
[`svg-react-loader](https://github.com/jhamlet/svg-react-loader)
[svg-to-react-cli](https://github.com/goopscoop/svg-to-react-cli)
[react-svg-loader](https://github.com/boopathi/react-svg-loader)

Thanks.

**Comment by finneganh** [comment]
Are you trying to animate the SVG or just have the SVG in an animated component?

I think I used react-svg-loader at Fabric, but never tried to animate the internals of a sprite.

**Comment by saniko** [comment]
Hi,
Thank for the quick reply!
I'm aiming to animate the SVG as a functional component.

Just making sure no known issues or limitations with velocity-react and SVG animation (react component from loader) before I dive deeper ;)

Thanks.
