### ISSUE TITLE
How to unmount invisible component with VelocityComponent?

### ISSUE THREAD

**Issue by rico345100** [twitter-fabric/velocity-react#163]
Like this:

```javascript
class AnimatedComponent extends Component {
	state = {
		show: true
	}
	toggleShow = () => {
		this.setState({ show: !this.state.show });
	}
	render() {
		const { show } = this.state;
		
		return (
			<div>
				<button onClick={this.toggleShow}>Toggle</button>

				<VelocityComponent animation={{ opacity: show ? 1 : 0, visibility: show ? 'visible' : 'hidden' }} duration={300}>
					<SubComponent />
				</VelocityComponent>
			</div>
		)
	}
}

class SubComponent extends Component {
	render() {
		return <h1>Helloworld</h1>;
	}
}
```

When clicked the button, Helloworld text will disappear, but it sill block the size. Another animation library, like React-Motion, unmounts component automatically, but velocity-react looks like not. Is there a way to unmount component after being invisible?

**Comment by finneganh** [comment]
Right, hidden components will still take up space.

I'd recommend using `VelocityTransitionGroup`. That will let you run an animation when the component is unmounted. Just change your logic to no longer render the component, and the library will animate it away.
