### ISSUE TITLE
Its possible to pass command to VelocityComponent?

### ISSUE THREAD

**Issue by kresli** [twitter-fabric/velocity-react#165]
Taken from velocity's documentation`.velocity("scroll", { duration: 1500, easing: "spring" })`, however I'm not able to find out how can I pass such props. If such a feature missing, then maybe consider following
```
<VelocityComponent duration={200} animation={{axis:'x', offset:250}} command="scroll">
```

**Comment by finneganh** [comment]
It should be the case that you want the `animation` prop to be `"scroll"`, then pass the `duration` and `easing` as props to `VelocityComponent`.

From the `VelocityComponent` docs: “Unrecognized properties are passed as options to Velocity (e.g. duration, delay, loop).”

**Comment by kresli** [comment]
Thanks, sounds logical. However I'm unable to animate it anyway. 
```
<VelocityComponent animation="scroll" duration={5000} axis="x" offset={400}>
```

**Comment by kresli** [comment]
Never mind, I didn't realise the proper syntax. Thank you though.
