### ISSUE TITLE
 'duration' property takes no effect, any idea?

### ISSUE THREAD

**Issue by saniko** [twitter-fabric/velocity-react#166]
Hi,
Any idea on why the 'duration' property takes no effect?
Any number I provide, the animations just flicks.

I would like to animate the arrow as a CTA.

`     <VelocityComponent animation={{translateY:10}} duration={800} loop={true}>
                   <Arrow className='arrow' width='100' height='100' onClick={()=>this.scrollTo('section2')}/>
               </VelocityComponent>`

Thanks.

**Comment by finneganh** [comment]
Does leaving off the `loop` param change anything?

**Comment by saniko** [comment]
This has been solved with the runOnMount property.
