### ISSUE TITLE
using together with materializecss

### ISSUE THREAD

**Issue by smeijer** [twitter-fabric/velocity-react#167]
I've also posted a topic on the [materializecss issue tracker](https://github.com/Dogfalo/materialize/issues/4211); but I'm not really convinced I will find my answer there.

When using this library together with materializecss, the velocity library of materialize is being used. Materialize seems to bundle this dependency themselves, what makes it hard to change anything.

Currently, velocity is throwing an error, that the `finishAll` method cannot be found. 

> Uncaught (in promise) Error: Velocity: First argument (finishAll) was not a property map, a known action, or a registered redirect. Aborting.

Any idea how we can fix this, or work around it? 

Error is happening on the `enter` event with an `slideDown` animation.

**Comment by finneganh** [comment]
You’ll need to make sure that you’re using Velocity 1.2.3 or later. I'm not sure how materialize is bringing it in, I couldn't obviously see from their code. You could poke around in Velocity to see how it attaches to `window`; I’m not sure if requiring a later Velocity would overwrite the earlier one globally.
