### ISSUE TITLE
'window is not defined' with isomorphic app

### ISSUE THREAD

**Issue by kkarkos** [twitter-fabric/velocity-react#168]
Hi, I wanted to implement `velocity-react` after reading (https://github.com/twitter-fabric/velocity-react#user-content-server-side-rendering) it supports server side rendering. 

When registering the lib on the server (express/node) I get :
```
node_modules/velocity-animate/velocity.js:417
})(window);
   ^
```

`ReferenceError: window is not defined`

Which is okay, because on the server there is no `window` object. I was reading that this has been an issue before and closed:
https://github.com/twitter-fabric/velocity-react/issues/14

Has this been solved and integrated? Do I miss something?

**Comment by finneganh** [comment]
Are you importing Velocity directly? The library should avoid this issue for itself through `lib/velocity-animate-shim.js`. Maybe look in there and see if you can tell why it's trying to do the real import server-side.
