### ISSUE TITLE
'window is not defined' error when importing 'velocity-animate'

### ISSUE THREAD

**Issue by saniko** [twitter-fabric/velocity-react#169]
HI,

I'm trying to animate the opacity of a specific container.
Basically, each 2 seconds I'm triggering render by setting state, the Image component gets updated with a background image, but no opacity animation.

the markup is very simple:

`<div className='col-md-3 col-sm-3'>
                                      <VelocityTransitionGroup enter={this.enterAnimation} leave={this.leaveAnimation}>
                                         <Image imageSelected={this.imageSelected} data={this.state.data[displayData]} />
                                      </VelocityTransitionGroup>
                                  </div>`
` enterAnimation()  {
    return  {
        animation: { opacity: 1 },
        duration: 500,
      }
  };

  leaveAnimation() {
    return {
        animation: { opacity: 0 },
        duration: 500
      }
  }`
Any idea?

if I'm importing the complementary packages:
`import 'velocity-animate';
import  'velocity-animate/velocity.ui';`

I'm getting the 'window is not defined' error message.

All packages are the latest version.

What am I doing wrong?

Thanks.

**Comment by finneganh** [comment]
Only import velocity and velocity.ui in your client code’s entry point. Use `velocity-react` elsewhere in your components and it should avoid loading velocity on the server.

**Comment by saniko** [comment]
Thanks.
