### ISSUE TITLE
Support for React 0.14

### ISSUE THREAD

**Issue by damassi** [twitter-fabric/velocity-react#17]
When attempting to install I'm getting a peer-requirements error since its looking for React 0.13

**Comment by jmfurlott** [comment]
@damassi Fixed this in the PR.  You can upgrade npm though to 3+ and get passed this error in the meantime for this, and any other, project

**Comment by phopkins** [comment]
Thanks for bringing this to my attention. That `react-dom` bit will be a bit annoying; I think I'll cut a branch for the RC until it's released, and then I think we'll need to do a hard cut over with a 1.1* release or somesuch.

* = might have to break out my semver docs… should it be 2.0 when the peerDependencies change so forcefully?

**Comment by damassi** [comment]
Thanks @jmfurlott - too scared to upgrade to the new npm just yet :)

**Comment by jmfurlott** [comment]
I am not too familiar with proper semver but I wouldn't upgrade this package to a major version unless just because React upgraded to a major version.  I would only go major if there are breaking changes/tons of new feature/etc relative to that project.

But at least a minor version :)

**Comment by phopkins** [comment]
Noticed that React 0.14 is now official: http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

Will look into getting support going in the very near term.

**Comment by Aaike** [comment]
good to hear :) would love to see support for 0.14 ! :+1:

**Comment by Glench** [comment]
Oh cool, looks like #19 fixes all of the breaking changes. Looking forward to it!

**Comment by phopkins** [comment]
Now fixed in v1.1.0 of velocity-react.
