### ISSUE TITLE
targetQuerySelector example

### ISSUE THREAD

**Issue by saniko** [twitter-fabric/velocity-react#171]
I'm trying to animate a group of elements in such a way 
that they will slidedown one by one when coming to viewport.

In velocity i can do this:
`$(".box").velocity "transition.slideDownIn", 
  stagger: 250,
  drag: true,
  duration: 2000,
......`

see: https://codepen.io/icebob/pen/NPwXaX
If I understand correctly this can be achieved with targetQuerySelector ?
If so, can you please point me to an example

Thanks

**Comment by finneganh** [comment]
If all the elements are added to the `VelocityTransitionGroup` at once then you don’t need `targetQuerySelector`, just `stagger`.

This is shown in the “Add 5 Rows” part of the demo: https://github.com/twitter-fabric/velocity-react/blob/master/demo/examples/scrolling-group.jsx

Also note that `targetQuerySelector` is only for `VelocityComponent`, not `VelocityTransitionGroup`.
