### ISSUE TITLE
VelocityTransitionGroup animation issue 

### ISSUE THREAD

**Issue by saniko** [twitter-fabric/velocity-react#174]
Hi,
Any idea about what I'm doing wrong?

 ` render() {

    var enterAnimation = {
               animation: 'fadeIn',//{opacity: 1},
               duration: 600
           }

    var leaveAnimation = {
               animation: 'fadeOut',//{opacity: 0},
               duration: 400,
               style: {display: 'none'}
           }

    return (

            <div className='container logos'>
                  <div className='col-md-3 col-sm-3'>
                    <VelocityTransitionGroup enter={enterAnimation} leave={leaveAnimation}>
                      <Image data={this.state.data} />
                    </VelocityTransitionGroup >
                  </div>
            </div>

    );
  }`

Every second the data attribute on the Image component changes, no animation.
If I add runOnMount={true} only enter animation runs ones.

**Comment by finneganh** [comment]
React is reconciling that to be the same `<Image>` component. Use a different `key` to force React to treat the `Image` as distinct.
