### ISSUE TITLE
npm run demo not working

### ISSUE THREAD

**Issue by mt1140600** [twitter-fabric/velocity-react#175]
on running npm run demo the terminal shows
> velocity-react@1.2.1 demo /home/raghav/Desktop/Prokure/velocity-react
> webpack-dev-server --progress --colors --content-base demo --hot --inline --config demo/webpack.config.js

 40% 1/2 build modulesevents.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:893:11)
    at exports._exceptionWithHostPort (util.js:916:20)
    at Server.__dirname.Server.Server._listen2 (net.js:1246:14)
    at listen (net.js:1282:10)
    at net.js:1391:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

npm ERR! Linux 4.4.0-66-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "demo"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! velocity-react@1.2.1 demo: `webpack-dev-server --progress --colors --content-base demo --hot --inline --config demo/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the velocity-react@1.2.1 demo script 'webpack-dev-server --progress --colors --content-base demo --hot --inline --config demo/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the velocity-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --progress --colors --content-base demo --hot --inline --config demo/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs velocity-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls velocity-react
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/raghav/Desktop/Prokure/velocity-react/npm-debug.log

**Comment by finneganh** [comment]
Error message seems to indicate you have something else running at port 8080 on that machine.

**Comment by mt1140600** [comment]
Thanks! I made it run on a different port and it worked :+1:
