### ISSUE TITLE
"Uncaught (in promise) Error", Any idea why I'm getting this error?

### ISSUE THREAD

**Issue by saniko** [twitter-fabric/velocity-react#178]
Latest velocity-react and velocity code.
No duplicated files

Uncaught (in promise) Error: Minified React error #119; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=119 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

non help with the decoder...

How to mitigate?

**Comment by finneganh** [comment]
It sounds like multiple React versions on the page so certainly double-check that in your node_modules. Other than that I’m not sure.

`velocity-react` doesn’t use refs itself, though `ReactTransitionGroup` does.

**Comment by saniko** [comment]
Strange, it happens on a specific component that renders nested animated component, and
only on prod build.
No issue with other animations.

**Comment by saniko** [comment]
Strange, it happens on a specific component that renders nested animated component, and
only on prod build.
No issue with other animations.

It's related to this issue:
#174

**Comment by finneganh** [comment]
What does the code look like?

**Comment by saniko** [comment]
Realy not sure if it's related 100% to velocity-react, but when I remove the animation from the Image component, all works.
It happens only on prod build (webpack), but I get no other errors, so debugging is hard,
Just wanted to check if any of you have an idea?

Do you see any issues here?

`var enterAnimation = {
           animation: {opacity: 1},
           duration: 600
       }

var leaveAnimation = {
           animation: {opacity: 0},
           duration: 400,
           style: {display: 'none'}
       }

return (
        <div className='container logos'>
               { this.state.displayData.map((displayData, index) => {
                  <div key={index} className='col-md-3 col-sm-3'>
                    <VelocityTransitionGroup enter={enterAnimation} leave={leaveAnimation}>
                      <Image key={Math.floor(Math.random()*10)} data={this.state.data} />
                    </VelocityTransitionGroup >
                  </div>
                  }
              )}
        </div>

);`

**Comment by saniko** [comment]
Realy not sure if it's related 100% to velocity-react, but when I remove the animation from the Image component, all works.
It happens only on prod build (webpack), but I get no other errors, so debugging is hard,
Just wanted to check if any of you have an idea?

Do you see any issues here?

`
var enterAnimation = {
           animation: {opacity: 1},
           duration: 600
       }

var leaveAnimation = {
           animation: {opacity: 0},
           duration: 400,
           style: {display: 'none'}
       }

return (
        <div className='container logos'>
               { this.state.displayData.map((displayData, index) => {
                  <div key={index} className='col-md-3 col-sm-3'>
                    <VelocityTransitionGroup enter={enterAnimation} leave={leaveAnimation}>
                      <Image key={Math.floor(Math.random()*10)} data={this.state.data} />
                    </VelocityTransitionGroup >
                  </div>
                  }

              )}
        </div>

);
`

**Comment by saniko** [comment]
Not sure it's related to velocity-react, but once i remove the animation, i get no errors.
Do you see any issues with this code?
Happens only on production build (webpack)

```
var enterAnimation = {
           animation: {opacity: 1},
           duration: 600
       }

var leaveAnimation = {
           animation: {opacity: 0},
           duration: 400,
           style: {display: 'none'}
       }

return (
        <div className='container logos'>
               { this.state.displayData.map((displayData, index) => {
                  <div key={index} className='col-md-3 col-sm-3'>
                    <VelocityTransitionGroup enter={enterAnimation} leave={leaveAnimation}>
                      <Image key={Math.floor(Math.random()*10)} data={this.state.data} />
                    </VelocityTransitionGroup >
                  </div>
                  }

              )}
        </div>

);

```

**Comment by finneganh** [comment]
I suspect that the issue is the `VelocityTransitionGroup` is being removed from the DOM while the transition around the `Image` is still going on.

You should in general have your `VelocityTransitionGroup`s be stable on the page, and only their contents appear and disappear.
