### ISSUE TITLE
Velocity.UI Server side rendering

### ISSUE THREAD

**Issue by lannex** [twitter-fabric/velocity-react#179]
Hi.
I'm going to use it on the server side.
But when i put a ``import 'velocity-animate/velocity.ui'``, i get a error message.

```
}((window.jQuery || window.Zepto || window), window, (window ? window.document : undefined));
	   ^

ReferenceError: window is not defined
```

And i put a ``import 'velocity-react/lib/velocity-animate-shim'`` 
Same a massage.

What should i do?

Thank you anyway~!

**Comment by finneganh** [comment]
You'll need to do your own `window` detection around a `require` for velocity.ui.
