### ISSUE TITLE
Velocity Component Slide animation

### ISSUE THREAD

**Issue by mt1140600** [twitter-fabric/velocity-react#180]
When I use Velocity Component to slide a tab panel what happens is the panel first gets viewd for a very short span and after it the slide animation starts. How to rectify it. On making the ta panel child of velocity component it shows error that no. of tab and tabPanels should be same

<VelocityComponent  animation={animation} duration = {2000} >
      <TabPanel key={index} >
        <DynamicTabPanel/>
      </TabPanel> 
      </VelocityComponent>

**Comment by finneganh** [comment]
You may be able to start the tab with display: none, and I believe that Velocity may show it automatically.

**Comment by mt1140600** [comment]
Yes the tab panel is getting displayed even without velocity component. So you want me to make its display none?

**Comment by finneganh** [comment]
You could give it a try but you'll probably have to do some digging yourself to see how the tabs are interacting with velocity.
