### ISSUE TITLE
Getting a flash with SSR

### ISSUE THREAD

**Issue by jpsear** [twitter-fabric/velocity-react#181]
My components seem to mount without animating from the server (if I switch off JavaScript), but as the client kicks in, the components then flash and animate in. Am I doing something wrong here? The expected behaviour is that there are no animations when visiting a page from the URL bar, but as you then continue to click around, animations happen as normal (on mount).

Here is my animation code:

```js
    const animationProps = {
      enterShowStyle: { display: '' },
      component: 'div',
      runOnMount: isClient(),
      enter: {
        animation: 'transition.slideUpIn',
        duration: 600,
        delay: this.props.delay
      }
    }

  <VelocityTransitionGroup {...animationProps}>
    {this.props.children}
  </VelocityTransitionGroup>
```

My `isClient()` method returns false on the server and true on the client. This is my effort at getting rid of the flash, which isn't working.

Thanks!
James

**Comment by finneganh** [comment]
The velocity animations don't run at all on the server. You'll want to display:none the element yourself and let velocity show it on the client.
