### ISSUE TITLE
Can't use slideLeft or slideRight as an animation type with VelocityTransitionGroup?

### ISSUE THREAD

**Issue by mr-e-** [twitter-fabric/velocity-react#182]
I have been able to use fadeIn and fadeOut, not sure why slide doesn't work? I'd like to make a React page transitions that looks like ios screen transitions. Is this possible?

```
<VelocityTransitionGroup
              enter={{animation: 'slideLeft'}}
              leave={{animation: 'slideLeft'}}>
        {this.cloneChildren()}
</VelocityTransitionGroup>
```

Uncaught (in promise) Error: Velocity: First argument (slideLeft) was not a property map, a known action, or a registered redirect. Aborting.
    at animate (velocity.js:2930)
    at velocity-transition-group.js:351

**Comment by finneganh** [comment]
Velocity doesn't have a `slideLeft` built in. The UI pack has `transition.slideLeftIn` and `transition.slideLeftOut` as preregistered effects, however.

http://velocityjs.org/#uiPack
