### ISSUE TITLE
PropTypes deprecation from react 15.5

### ISSUE THREAD

**Issue by ZebraFlesh** [twitter-fabric/velocity-react#183]
Using `VelocityTransitionGroup` with react 15.5 generates the following deprecation notice:

```Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.```

Replacing `React.PropTypes` with `PropTypes` (via `import PropTypes from 'prop-types';`) in VelocityComponent and VelocityTransitionGroup should resolve this issue.

**Comment by finneganh** [comment]
Thanks for the heads up. Will I think also move
to reactjs/react-transition-group in the next release.

**Comment by finneganh** [comment]
#191 has fixes for this if you're able to try it out. I had to change some of the internals and also add a prepublish step to this library in order to use ES2015 classes so i want to do a careful rollout.

**Comment by finneganh** [comment]
Fixed in v1.3.0. Thanks for your patience!
