### ISSUE TITLE
react-addons-transition-group@15.5.2 This package is deprecated and will no longer work with React 16+

### ISSUE THREAD

**Issue by haunguyen90** [twitter-fabric/velocity-react#193]
I got the warning message when using velocity-react package say: 
"react-addons-transition-group@15.5.2: This package is deprecated and will no longer work with React 16+. We recommend you use TransitionGroup from 'react-transition-group' instead."
Please consider updating the dependency

**Comment by hoflish** [comment]
1. install the new package
    **yarn**: `yarn add  react-transition-group@1.1.1` 
    **npm**:  `npm install --save react-transition-group@1.1.1`

2. then import 
`import ReactTransitionGroup from 'react-transition-group/TransitionGroup';`

npm package : https://www.npmjs.com/package/react-addons-transition-group

**Comment by finneganh** [comment]
Fixed in v1.3.0. Thanks for your patience!
