### ISSUE TITLE
Add requiring information to the readme

### ISSUE THREAD

**Issue by danielo515** [twitter-fabric/velocity-react#194]
Hello,

I think it will be ideal to add some instructions about how to require this module to the usage section of the readme.
Not a big deal, but can confuse beginners.

It should be very straightforward, specially knowing that this information exist already as a comment on index.js:
https://github.com/twitter-fabric/velocity-react/blob/master/index.js#L3-L7

**Comment by finneganh** [comment]
FF to open a pull request!
