### ISSUE TITLE
Options hash in VelocityComponent using Velocity UI Pack

### ISSUE THREAD

**Issue by jwdinker** [twitter-fabric/velocity-react#202]
Outside of velocity-react you can pass in an options hash to a velocity ui pack animation like so...

`$elements.velocity("callout.bounce",{duration:500 ....);`

I was confused in the documentation where it says :

_Unrecognized properties are passed as options to Velocity (e.g. duration, delay, loop)._

Just needed some clarification that if you are using a VelocityComponent with velocity UI pack transitions like 'transition.slideLeftIn', you have to use registerEffect to add these options?

**Comment by finneganh** [comment]
This means you can do:

`<VelocityComponent animation="transition.slideLeftIn" duration={500} delay={1000} />`

“unrecognized” in this case means props that aren’t handled directly by `VelocityComponent`.
