### ISSUE TITLE
timer typo

### ISSUE THREAD

**Issue by dmeiz** [twitter-fabric/velocity-react#203]
Howdy,

I think this should be `frame` instead of `timer`.

https://github.com/twitter-fabric/velocity-react/blob/801b7701f6cedc56951015c88898a34a54c612f9/src/velocity-transition-group.js#L142

Thx,
Dan

**Comment by finneganh** [comment]
Eeep. Good catch. Thanks!

**Comment by finneganh** [comment]
Fixed in v1.3.3
