### ISSUE TITLE
Problem with animation sequence with delay

### ISSUE THREAD

**Issue by maximusnikulin** [twitter-fabric/velocity-react#205]
Hi there. Thanks for that great project, it's really nice. Could you help me please, I want to animate my block one by one, depending on some conditions like props on my parent component. First of all I want to animate translateY property, and after that translateX, but when condition changes I want to reverse it - change translateX, and change translateY after that.
I know that there is **complete** callback, but It would be great to not use state for this, because of my animation will be triggered on scroll event and I don't want to rerender all component.
How can I achieve that?
I'll be grateful for any ideas you'll give, thanks.
That's my code:
```javascript
   <VelocityComponent 
                        animation = {
                            {
                                translateY: this.props.collapse ? -300 : 0,                        
                            }
                        }
                        duration = {500}                        
                        delay = {500}>                                                               
                            <i className = 'points__item'></i>
                    </VelocityComponent >  
```

**Comment by finneganh** [comment]
You can chain animations using UI pack and `VelocityHelpers.registerEffect`. The API syntax is a little wonky, just pass additional elements in the `calls` array property when you register the animation. Velocity will run the first animation, then run the second. That will let you chain the two translates without any explicit effort on your part.

**Comment by maximusnikulin** [comment]
Could you get me some example for it ?

**Comment by finneganh** [comment]
Here’s an example of `registerEffect` with a single call: 

https://github.com/twitter-fabric/velocity-react/blob/master/demo/examples/flap-box.jsx#L18

add more to the `calls` array to chain effects.

**Comment by maximusnikulin** [comment]
I'll try this out, thanks a lot

**Comment by maximusnikulin** [comment]
I have tried this, it works for one direction, but it seems that it don't recognise delay property on reverse direction.
That's my code:
```javascript 
 <VelocityComponent 
                        key = {i + '' + j}                        
                        animation = {
                            velocityHelpers.registerEffect({ 
                                defaultDuration:1000,                               
                                calls: [
                                    [{  translateY: this.props.collapse ? -(this.fullHeight - 150 + topOffset) : 0}, 1, delay: 500],                                                                                    
                                    [{  translateX: this.props.collapse ? -leftOffset : 0 }, 1, {delay: this.props.collapse ? 500 : 0}],            
                                ],
                                
                            })                            
                        }
                        >                                                               
                            <i className = 'points__item'
                            style = {{                                                        
                                    top: topOffset + 'px',
                                    left: leftOffset + 'px',
                                }}></i>
                    </VelocityComponent >
```
Do you have any ideas, I am really exhausted by it. I hope for your help, thanks

**Comment by finneganh** [comment]
You should define the two animations outside of your render method, one for collapse and one for not-collapsed, and then use `this.props.collapse` to choose which one to pass as `animation`.
