### ISSUE TITLE
Use import instead of require

### ISSUE THREAD

**Issue by clem91** [twitter-fabric/velocity-react#214]
Hi!

I used stock velocity and now i'm playing with react and I found your wrapper which seems really good!
I was wondering if you already implemented an es6 manner of calling your library (import) ?

**Comment by hirenumradia** [comment]
Hey,

Take a look at this, I think this answers your question. <3

https://codesandbox.io/s/5K3yjOpq

**Comment by clem91** [comment]
Thanks it's exactly what I was looking for!
