### ISSUE TITLE
Cross Component height transition doesn't work

### ISSUE THREAD

**Issue by switchnollie** [twitter-fabric/velocity-react#226]
I decided to use velocity-react to transition height on a component with height auto as this is not possible in CSS. 
Based on the this.state.inEditingView, either the component `<SettingsDropdownForm />` (`<form>...</form>` element) or the component `<SettingsDropdownList />` (`<ul>....</ul>` element) is rendered. 
Wrapping this JSX conditional into a VelocityTransitionGroup with slideDown/slideUp animation doesn't do the job, the container changes its height immediately and the created div for the VelocityTransitionGroup keeps its dimensions.
The approach somehow works if the condition is just between rendering one of the components and not rendering anything so how would be the correct approach for a cross component transition?

```js
<div id="settings-dropdown-menu" className={this.state.isOpened ? "dropdown-menu dropdown-menu-active shadow-z-1" : "dropdown-menu"}>
   <VelocityTransitionGroup component="div" enter={{animation: "slideDown"}} leave={{animation: "slideUp"}}>
      {!this.state.inEditingView ? <SettingsDropdownList  /> : <SettingsDropdownForm /> }
   </VelocityTransitionGroup>
</div>
```

**Comment by finneganh** [comment]
Not sure quite what effect you’re going for, but using VelocityTransitionGroup to switch between two views is just going to be tricky. During transition, you’ll likely have both views appearing, messing up the parent height. 

Good luck in debugging. I tend to slow the animations way down to see what’s going on in detail. 

I have done a cross fade in the past, between two views of the same height. The trick is to set the leaving one to position absolute so it can exist in the same space as the entering one.
