### ISSUE TITLE
Is this project still being developed?

### ISSUE THREAD

**Issue by mduleone** [twitter-fabric/velocity-react#256]
Google is [EOL'ing Fabric in March 2020](https://get.fabric.io/roadmap), should we expect Velocity and Velocity-React to EOL with Fabric at the same time?

**Comment by fionawhim** [comment]
Velocity isn’t a Google product, so no worries there. 

As far as this project, it’s basically already been maintenance mode for a few years now. I’ll keep updating it for new React releases as long as it’s not too hard.

**Comment by Toshinaki** [comment]
@fionawhim 
Thanks for the great work.

It's been almost 2 years since last update.
Is there any chance for some updates adapting to React's new features?

**Comment by fionawhim** [comment]
I’m not expecting to proactively make any changes to this library past what would be necessary for compatibility with React updates at my current employer (which isn’t Google).

**Comment by Toshinaki** [comment]
@fionawhim 
OK, thanks, good to know.
So who's in charge of this repo now?

**Comment by fionawhim** [comment]
:shrug:
