### ISSUE TITLE
Update react-transition-group

### ISSUE THREAD

**Issue by manugb** [twitter-fabric/velocity-react#257]
Dep is two majors down, right now it sits at 4.3.0

https://github.com/reactjs/react-transition-group

**Comment by fionawhim** [comment]
@manugb What problems are you seeing by `velocity-react` depending on 2.x.x?

**Comment by manugb** [comment]
We updatede to latest, and we experience some issues regarding height of a comp inside a transition group, we fixed going back to 1.3.3

There is nothing wrong with 2.x besides this. But anyway rtg is at 4.x, staying up to date help with with transitive deps and less code to the client

**Comment by fionawhim** [comment]
Happily it seems that v4 doesn’t have any API changes, the breaking changes are due to ESM stuff and React min versions.

Updating dependencies is typically something I look at when new React major versions land, to avoid warnings and such for the poor souls who still use this abandoned library.
