### ISSUE TITLE
chaining with react components

### ISSUE THREAD

**Issue by larryhengl** [twitter-fabric/velocity-react#26]
Hey Folks, this looks interesting, nice work!

How would you recommend chaining velocity animations across components (sync or async)?  For example,
1 Component on left side of page, 2 Components stacked on right side:

| Comp1 | Comp2 |
| ---------- | --------- |
| | **Comp3** |

pseudo...
```javascript
<div id=left>
  <Comp1 />
</div>
<div id=right>
  <Comp2 />
  <Comp3 />
</div>
``` 

I would like to fadeIn/Out Comp1 on a button click.  When fading I would also like to fade or slide the right side to full width, sorta like your typical slideout menu effect.  

I also want to fadeIn/Out Comp2 on a button click, and nicely slide or fade Comp3 in its place.

So far using bootstrap grid classes for spacing, but the collapsing effects are still too sudden.
For example, I fadeOut Comp1, and apply the class col-md-12 to Comp2 and Comp3. But the class is applied by state change outside of the VelocityComponent, so the right side drops below the left side until the animation is done.  Icky. Was thinking fade both sides out, then fade right side back in.

pseudo...
```javascript
<VelocityComponent>
  <div id=left>
    <Comp1 />
  </div>
<VelocityComponent />
<VelocityComponent>
  <div id=right>
    <VelocityComponent>
      <Comp2 />
    <VelocityComponent />
    <VelocityComponent>
      <Comp3 />
    <VelocityComponent />
 </div>
<VelocityComponent />
``` 

The Velocity docs show chaining but for jquery methods, not React.  And the TransitionGroup example seems to show animation sequences applied to one component only, not across sibling components...based on my noob understanding.

Thoughts?

Cheers,
:Larry

**Comment by phopkins** [comment]
I think the best way to achieve a "chaining" effect with these components is to just use a `delay` on the 2nd animation that matches the `duration` of the first. (You can use a constant or something to keep the 2 values in sync.)

For your problems above, you need to decide whether you're doing your widths in JS with styles/animations or in CSS with classes. Mixing the 2 will likely give you popping issues like you describe. (You may want to consider CSS `transition`s, for example, which should play well with the classes.)

Not sure what you're trying to achieve on the right side, but bear in mind that if 2 elements need to take up the same space, absent negative margin shenanigans you'll need some amount of absolute positioning. The `LoadingCrossfadeComponent` in the demo code may give you an effect you want, though bear in mind it can be slightly finicky to get working.


(Closing this as it is not an issue in `velocity-component`)
