### ISSUE TITLE
React 0.14 "refs must have owner" error

### ISSUE THREAD

**Issue by TCMiranda** [twitter-fabric/velocity-react#28]
Guys, hello!

I am having some trouble, maybe because I don't get yet what `Uncaught Error: Invariant Violation: addComponentAsRefTo(...)` is, but here's whats happening:

I added the following code to help me with my pages transition
![captura de tela de 2015-10-11 10 04 00](https://cloud.githubusercontent.com/assets/10077439/10416869/6df617ce-6fff-11e5-8b2c-820b8b8cf38a.png)

The key is related to the current page, so when the page changes, it renders a component with another key, creating the transition.

When updated to React 0.14 that code gives me
![captura de tela de 2015-10-11 10 07 20](https://cloud.githubusercontent.com/assets/10077439/10416876/e28d3ca2-6fff-11e5-98bb-f6b1142b30da.png)

Works using any other parent 
![captura de tela de 2015-10-11 10 20 10](https://cloud.githubusercontent.com/assets/10077439/10416933/a9a3150e-7001-11e5-953a-0e3719bfb0cf.png)

So I think it is not related to the ` {[ child ]}` I created, right?

I also checked the `<VelocityTransitionGroup />` but I cant find any refs being used.

Thanks!!

**Comment by Mtpc** [comment]
If you're using a module bundler such as webpack, check that velocity-react doesn't bring its own react module (that is, react mustn't appear in its `node_modules` folder).
If that's not the case, then just remove and reinstall velocity-react, npm will know that you already depend on react and won't install it again as a peer dependency, which won't lead to a duplicate copy of react loaded when you use `VelocityTransitionGroup` (or any other velocity-react component for that matter)

**Comment by phopkins** [comment]
Yeah, that error commonly means that you have 2 React instances. velocity-react uses peerDependencies so it typically doesn't bring in its own React. You should try `npm dedupe` to prune your tree down to one React. 

Note that this can also come up if you are `npm link`ing to a velocity-react directory that has all its dependencies installed. To test locally, you'll need to `npm pack` and then `npm install` the archive it creates.
