### ISSUE TITLE
VelocityTransitionGroup to manage page transitions with react-router

### ISSUE THREAD

**Issue by arush** [twitter-fabric/velocity-react#29]
Hi,
Could you publish an example of how to use VelocityTransitionGroup to manage page transitions with react-router both v1.0.0 syntax and the older react-router syntax? 

Many thanks,

**Comment by phopkins** [comment]
I haven't much used react-router myself. Can anyone else chime in here?

The one I'm most familiar with is https://github.com/larrymyers/react-mini-router, which should work pretty trivially with `VelocityTransitionGroup`. Just call `renderCurrentRoute` as a child of `VelocityTransitionGroup`.

**Comment by mars** [comment]
The key to animating React Router transitions is to add a unique `key` prop to the route's children, so that the transition group recognizes that the components are changing.

Example of a Route component that animates its children's transitions:

```javascript
class AppView extends React.Component {
  render() {
    const { pathname } = this.props.location;
    const key = pathname.split('/')[1] || 'root';

    return (
      <div id="app-view">
        <VelocityTransitionGroup 
          enter={{animation: "slideDown"}}
          leave={{animation: "slideUp"}}>

          {React.cloneElement(this.props.children || <div />, { key: key })}

        </VelocityTransitionGroup>
      </div>
    );
  }
}
```

(React 0.14, React Router 1.0.0-rc3, Velocity React 1.1.0)

**Comment by phopkins** [comment]
Thanks, @mars!

I'll also add that for stuff like this, where your `VelocityTransitionGroup` has single elements that are coming and going, you may need to use absolute positioning during the transition to get overlap right. Take a look at the `LoadingCrossfadeComponent` in the demo source code to see one way of doing this.

**Comment by py-in-the-sky** [comment]
@phopkins I really like how absolute positioning, if I understand it correctly, is applied only for the transition in `LoadingCrossfadeComponent`.

Here's an example of how I've done it with react-router, but I plan revising it to follow the example of `LoadingCrossfadeComponent`:

* [PageHandler](https://github.com/py-in-the-sky/gae-flask-redux-react-starter-kit/blob/master/browser_client/src/app/components/PageHandler.js) animates incoming/outgoing pages.

* [Layout](https://github.com/py-in-the-sky/gae-flask-redux-react-starter-kit/blob/master/browser_client/src/app/components/Layout.js) passes pages as children to PageHandler.

* The [app root](https://github.com/py-in-the-sky/gae-flask-redux-react-starter-kit/blob/master/browser_client/src/app/containers/index.js#L72) uses react-router to define how pages are passed to LayoutApp, which wraps Layout.

**Comment by py-in-the-sky** [comment]
[Here's](https://github.com/rackt/react-router/blob/master/examples/animations/app.js) an example from the react-router repo.  It uses `ReactCSSTransitionGroup` instead of velocity-react, but the same design principles apply.
