### ISSUE TITLE
Ability to pass in a hash of start properties before animation

### ISSUE THREAD

**Issue by damassi** [twitter-fabric/velocity-react#30]
It would be nice to be able to declaratively say what should happen as opposed to setting a style, and then wrapping the <velocity> component around it, and then having velocity compute from there.

What I'm thinking is something along the lines of TweenMax's `fromTo` method:

```
TweenMax.fromTo({ top: 100, opacity: 0}, { 
    top: 0, 
    opacity: 1
}) 
```

This method immediately sets the properties on a component before it is animated, and then animates from there. Right now I don't see a way to achieve this, unless this requires TransitionGroup (which seems a bit much for a fire and forget sort of thing).

**Comment by phopkins** [comment]
I think what you want is covered by Velocity, which allows for a start value when tweening:
```
<VelocityComponent animation={{top: [0, 100], opacity: [1, 0]}}>…</VelocityComponent>
```

(It's a bit counter-intuitive in that the second value in the array is the start, and the first is the end. It also only works for linear tweens AFAIK.)

Make sure that this is what you want, though. If you're changing animations back and forth, you'll get a smoother effect without fixing the start value.

**Comment by damassi** [comment]
ok cool, thanks so much; i'll give it a spin
