### ISSUE TITLE
First argument error

### ISSUE THREAD

**Issue by bnwan** [twitter-fabric/velocity-react#40]
I'm getting this error when I try to use VelocityComponent

Velocity: First argument (transition.slideLeftIn) was not a property map, a known action, or a registered redirect

Any ideas?

**Comment by phopkins** [comment]
Sounds like you don't have the Velocity UI Pack installed. At a top level of your app, include:

```javascript
require('velocity-animate');
require('velocity-animate/velocity.ui');
```
