### ISSUE TITLE
VelocityTransitionGroup does not work with radium

### ISSUE THREAD

**Issue by basarat** [twitter-fabric/velocity-react#41]
Radium https://github.com/FormidableLabs/radium 

If I add Radium decorator on the component -> then -> velocity transitions don't happen anymore. Probably because both libraries work off of `style` property.

> This issue is mostly for tracking / search-ability of *surprise* moment for new users :rose: Refs https://github.com/FormidableLabs/radium/issues/394

**Comment by phopkins** [comment]
Thanks for bringing this to our attention. I think it would be up to Radium to avoid stomping existing style attributes, but that may not be feasible. (Vanilla React appears to be well more tolerant of this, even with setting `style` hashes on your elements.)

In the immediate term, I'm not sure there's anything we can do, given how Velocity operates completely outside of React and on the DOM directly.

If you do any investigation and get a lead on an approach that might resolve the compatibility between the libraries, FF to re-open and let us know what you find.

**Comment by mars** [comment]
This can be easily worked-around by avoiding Radium styles on the component's root element. Instead,  nest a `<div>` to hold the Radium styles.

For example, replace this component's root element style:
```javascript
render() {
  return (
    <div style={{ display: 'flex' }}>
      <h1>{'Pure awesome'}</h1>
    </div>
  );
}
```

…with a nested structure:
```javascript
render() {
  return (
    <div>
      <div style={{ display: 'flex' }}>
        <h1>{'Pure awesome'}</h1>
      </div>
    </div>
  );
}
```

Any styles required on that root `<div/>` should be managed from the parent Velocity* component, using [the `style` prop](https://github.com/twitter-fabric/velocity-react#velocitytransitiongroup) & [forcefeeding](http://julian.com/research/velocity/#forcefeeding).

**Comment by ianobermiller** [comment]
>  it would be up to Radium to avoid stomping existing style attributes

Sorry, I haven't taken the time to try to debug this. What exactly is causing the incompatibility? Radium expects `style` to be either a normal style object or an array of such style objects, optionally augmented with special keys like `:hover` and `@media`.

**Comment by mars** [comment]
Sorry my late-night comment above does not address the bug reported; it's out of place. I do use Radium & Velocity React together successfully, so I was trying to help @basarat.

**Comment by ianobermiller** [comment]
Ah, sure, you will of course run into this if you are rendering the style element using React and then changing it using Velocity. This isn't Radium specific, and there is likely no way to avoid it other than using a container element to for Velocity, and Radium on the inside.
