### ISSUE TITLE
velocityHelpers can't be used in a server-side render environment.

### ISSUE THREAD

**Issue by Jon-Biz** [twitter-fabric/velocity-react#44]
The original `velocity-animate` package expects to be client-side, so `requiring` it, in order to enable the velocityHelpers, isn't possible when you are rendering on the server.

**Comment by phopkins** [comment]
Hrm. Good point. Let me look into this.

**Comment by phopkins** [comment]
Does #54 help you with this?

You'll still want to wrap your primary `require` calls in:
```
if (typeof window !== 'undefined') {
  …
}
```

and the `velocity-react` components will use their shim.

**Comment by cdebotton** [comment]
I'm still having the issue with `velocity-react`@1.1.1. I've wrapped the require for velocity-animate/velocity.ui in a check to determine if the code is being run in the browser environment, but I receive the error: 

```throw "Velocity.RegisterEffect not found. You need to require('velocity-animate/velocity.ui') at a top level for UI Pack.";```

Seem's like it's not no-op'ing on the server.

**Comment by phopkins** [comment]
Lemme get this reviewed and we can get a release up.

**Comment by phopkins** [comment]
Fixed in 1.1.2.
