### ISSUE TITLE
Simple example to toggle content

### ISSUE THREAD

**Issue by approots** [twitter-fabric/velocity-react#45]
A simple example for swapping content with animations would be helpful for me. The example for VelocityComponent works for toggle fading a single component in and out:

    <VelocityComponent animation={{ opacity: this.state.showSubComponent ? 1 : 0 }} duration={500}>
      <MySubComponent/>
    </VelocityComponent>

But I'm not sure how to proceed if I want to swap one component for another with a fadeout/fadein?

**Comment by approots** [comment]
I have a crude toggle working. The problem is that the incoming html takes space while the outgoing html fades out. I can set display:'none' for the "leave" animation, or I suppose I could use absolute positioning. Is there any way to delay and not mount the incoming html/component until the outgoing html/component fades out?

Anyway, here's the code:

    var MyComponent = React.createClass({

		getInitialState: function() {
			return {showNewComponent:false}
		},
		
		handleClick: function() {
			this.setState({showNewComponent: !this.state.showNewComponent});
		},

		render: function () {
			var enterAnimation = {
				animation: 'fadeIn',//{opacity: 1},
				duration: 800,
				//delay: 500
			};
			
			var leaveAnimation = {
				animation: 'fadeOut',//{opacity: 0},
				duration: 800,
				style: {display: 'none'}
			};
			
			return (
				<div style={{backgroundColor:'#E5F2FF'}}>
					<button onClick={this.handleClick}>Toggle</button>

					<VelocityTransitionGroup enter={enterAnimation} leave={leaveAnimation}>
						{this.state.showNewComponent ? undefined : <div>INITIAL COMPONENT</div> }
					</VelocityTransitionGroup>
					
					<VelocityTransitionGroup enter={enterAnimation} leave={leaveAnimation}>
						{this.state.showNewComponent ? <div>NEW COMPONENT</div> : undefined }
					</VelocityTransitionGroup>			
				</div>
			);
		},
	});

**Comment by phopkins** [comment]
Take a look at `LoadingCrossfadeComponent` in the demo code for how to switch an element to `absolute` as it leaves so that it doesn't take up space.

Putting a `delay` on the enter animation may work, but the danger there is additional stuttering of the height. (I suspect it would only be feasible if you can let the container collapse down to 0 height.)

**Comment by hellogerard** [comment]
You can put them all in the same transition group, if you like:

```
                <VelocityTransitionGroup enter={enterAnimation} leave={leaveAnimation}>
                    {this.state.showNewComponent ? undefined : <div>INITIAL COMPONENT</div> }
                    {this.state.showNewComponent ? <div>NEW COMPONENT</div> : undefined }
                </VelocityTransitionGroup>          
```
