### ISSUE TITLE
velocity-animate not available as documented

### ISSUE THREAD

**Issue by chrisdrackett** [twitter-fabric/velocity-react#47]
if I put the following code from the docs into my app:

    require('velocity-animate');
    require('velocity-animate/velocity.ui');

I run into errors. I think this is because velocity-animate is installed in the node_models for velocity-react, but isn't available to my main app. I can fix it with the following code, but this seems like a hack:

    require('velocity-react/node_modules/velocity-animate');
    require('velocity-react/node_modules/velocity-animate/velocity.ui');

**Comment by chrisdrackett** [comment]
actually the code I pasted below is causing issues with react, so I don't currently have a solution :)

**Comment by phopkins** [comment]
Are you using Webpack or some other packager that is aware of npm modules?
You'll need that for this library.

**Comment by chrisdrackett** [comment]
yeah, using web pack. I eventually got it to work, but only after removing node_modules and reinstalling. Everyone on my team had to do the same thing. Not sure what was going on, but its fixed now with a fresh install.

**Comment by phopkins** [comment]
Glad to hear it's working. This may have been an issue that could have been solved with `npm dedupe` as well.
