### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by msurguy** [twitter-fabric/velocity-react#49]
Hi! 

I've downloaded this repo and ran the commands specified in Readme but getting the error below which prevents me from running this locally.

![screen shot 2015-11-09 at 6 08 02 pm](https://cloud.githubusercontent.com/assets/585833/11052462/f7acd6aa-870c-11e5-8f81-79c4b75b4aca.png)

What could be the problem?

**Comment by RachBLondon** [comment]
Yeah I am also getting the same error. I have tried installing the latest react & react-dom, bur its still not working.  I am curious to get started with this, so appreciate any pointers - ta!

**Comment by PEM--** [comment]
That's due to an issue on `webpack-1.12.3`: https://github.com/webpack/webpack/issues/1596

In your `package.json`, set webpack and webpack-dev-server to their former releases:
```json
    "webpack": "1.12.2",
    "webpack-dev-server": "1.10.0 "
```

**Comment by PEM--** [comment]
`webpack-1.12.4` has just been published and it fixes this issue. @msurguy, you should close this.

**Comment by RachBLondon** [comment]
Thanks for getting back to me so quickly on this :-)

**Comment by phopkins** [comment]
Thanks for clearing this up, @PEM--!

**Comment by PEM--** [comment]
My pleasure. Thank you for sharing your library. I will surely use it for one of my next project.
