### ISSUE TITLE
Uncaught Velocity.RegisterEffect not found. however I do require('velocity-animate/velocity.ui').

### ISSUE THREAD

**Issue by miketamis** [twitter-fabric/velocity-react#50]
I am getting
```
Uncaught Velocity.RegisterEffect not found.
You need to require('velocity-animate/velocity.ui') at a top level for UI Pack.
```
However I do require Velocity UI in my top level component.

```js
import 'babel-core/polyfill';
import 'velocity-animate';
import 'velocity-animate/velocity.ui';
import ReactDOM from 'react-dom';
```

Velocity is on the window, but Velocity.RegisterEffect is not.

**Comment by phopkins** [comment]
Try doing an `npm dedupe` to make sure there aren't alternate Velocity runtimes being loaded.

Also, not sure how it pans out, but make sure some subtle difference between `import` and `require` isn't causing a problem, since the Velocity libs are not "pure" in the module sense.

**Comment by dcalhoun** [comment]
I ran into this same issue. The way I resolved it was adding `velocity-animate` as an [explicit dependency of my app](http://stackoverflow.com/a/9736561/378228). I'm not sure if this was the intended/best approach, but I am now able to require the two `velocity-animate` packages like so:

First:
`npm i -S velocity-animate`

Then:
```javascript
import 'velocity-animate'
import 'velocity-animate/velocity.ui'
import { VelocityTransitionGroup, velocityHelpers } from 'velocity-react'
```

**Comment by dcalhoun** [comment]
@finneganh I thought about this some more. Should velocity-animated be added as a `peerDependency` for this package?

**Comment by finneganh** [comment]
Not sure what the best practice is here. If you do a peerDependency, it
would need to be explicitly added as a dependency to the parent app.

I don't know enough about NPM to know when it puts transitive dependencies
in the package's root, and when they go into the sub-packages (though
version numbers may have something to do with it). It may also vary by NPM
version.

**Comment by dcalhoun** [comment]
I realize now that a parent project has to directly require `velocity-animate` *only* if you desire "to use the Velocity UI Pack" (from the [README](https://github.com/twitter-fabric/velocity-react/tree/v1.1.4#installation)). So, I suppose that rules out using `peerDependencies`.

I suppose a nice middle ground could be adding note to the README that you need to install `velocity-animate` yourself prior to directly requiring it. That may be common sense, but the wording of this project's README tripped me up.

Thanks for the help!

**Comment by finneganh** [comment]
Latest version has this tip in the README, in case it bites someone else.

**Comment by lauffenp** [comment]
Great library. However, I am still finding that I have to require the velocity helpers in my low-level components to get Velocity.RegisterEffect in my window. I have tried running `npm dedupe`, but I'm getting `Cannot read property 'localeCompare' of null` error, which I think is an npm issue.

Do you think this is really the problem? I have of course explicitly installed the velocity-animate package.

I'm happy to provide any additional info if it helps.

**Comment by finneganh** [comment]
@lauffenp what's the stack trace on that? Neither `velocity-react` nor `velocity` use `localeCompare` directly.
