### ISSUE TITLE
The hooks are behaving abnormally

### ISSUE THREAD

**Issue by minfawang** [twitter-fabric/velocity-react#55]
Below is a simple render function to illustrate the point:
~~~javascript
render () {
  const transition = {
    enter: {
      animation: {
        opacity: 1,
      },
      duration: 400,
      begin() {
        console.log('[Enter] begin');
      },
    },
    leave: {
      animation: {
        opacity: 0,
      },
      duration: 400,
      begin() {
        console.log('[Leave] begin');
      },
    }
  };

  return (
    <VelocityTransitionGroup {...transition}>
      {'Children Here'}
    <VelocityTransitionGroup />
  );
}
~~~

I noticed that when the children are added, the console prints:
~~~
[Leave] begin
[Enter] begin
~~~

I think this is a bug. Or is there a reason for this behavior? 
Thanks!!

**Comment by phopkins** [comment]
The `leave` animation is always finished on an element before the `enter` animation runs, to try to make sure that `enter` animations always have a consistent state.

Not sure either way on having the `begin` trigger in this case or not. Probably it shouldn't; actually #53 removes that behavior for complete, so perhaps they should be consistent.

What's your use case?

**Comment by phopkins** [comment]
Closing. Re-open w/ further information if this is causing problems.
