### ISSUE TITLE
issues getting measurements on element within VelocityTransitionGroup

### ISSUE THREAD

**Issue by chrisdrackett** [twitter-fabric/velocity-react#57]
I'm using a `VelocityTransitionGroup` for a `Loading` element that shows a spinner while it has no children and then fades the spinner out and fades the children in when they exist. The issue I'm running into is if I try and get the offsetWidth of a ref within the new children on componentDidMount I end up getting a value of 0. If I remove `VelocityTransitionGroup` I get the correct width value on this element.

Here is my Loading component for reference. the console log statement in `componentDidUpdate` returns a correct width pre and post loading without `VelocityTransitionGroup` but returns an incorrect value after loading otherwise:

https://gist.github.com/chrisdrackett/2dcbaea51b59166bf5db

**Comment by phopkins** [comment]
Does leaving out the `enter`/`leave` properties have any effect?

**Comment by chrisdrackett** [comment]
looks like if I leave out `enter` I don't have the same issue.

**Comment by phopkins** [comment]
OK. Animations start on a next tick so that all the animations for a single `VelocityTransitionGroup` can be collected and fired together (this makes things like `stagger` work). Your calculations are probably happening before the animations have started, which may be causing the issue.

**Comment by chrisdrackett** [comment]
I see, so is there any way to measure an element that is used in VelocityTransitionGroup?

**Comment by phopkins** [comment]
I think Velocity may have a "begin" callback that you could put on enter or
leave.

**Comment by chrisdrackett** [comment]
that would take care of the top level component, the issue here is that this affects any components mounting under the VelocityTransitionGroup.

**Comment by phopkins** [comment]
The Velocity animations are only applied to the direct children of
VelocityTransitionGroup, so if the tick over before animations starting is
what's giving you trouble with measurements, I would think that the begin
callback would fire when the components would be measurable.

**Comment by chrisdrackett** [comment]
right, but say I have a component inside the `Loading` component mentioned above. They also return a width of 0 on `ComponentDidMount` when they are the child of a `VelocityTransitionGroup`

**Comment by phopkins** [comment]
Are you measuring before or after Velocity kicks in and starts setting
styles?

**Comment by chrisdrackett** [comment]
the sub-components know nothing about velocity (its a couple components up the tree) and are trying to measure on `ComponentDidMount`. I'm not sure how to tell in what order things are happening at this point.

**Comment by chrisdrackett** [comment]
I'm guessing the problem is that the parent of the elements I'm trying to measure are set to `display: none`:

https://github.com/twitter-fabric/velocity-react/blob/master/velocity-transition-group.js#L153

which means that anything under that element will have a width/height of `0`

**Comment by chrisdrackett** [comment]
@phopkins confirmed that if I comment out the above line everything works as expected. I also tried replacing it with

`Velocity.CSS.setPropertyValue(node, 'opacity', '0');`

which might also suppress a flash, but without removing the ability to measure any children on mount.
