### ISSUE TITLE
Calls to window.requestAnimationFrame fail on IE 9

### ISSUE THREAD

**Issue by RandScullard** [twitter-fabric/velocity-react#64]
In velocity-transition-group.js, on lines 201 and 293, there are calls to window.requestAnimationFrame. This function is not available in Internet Explorer 9. The underlying Velocity library works on IE 9, and it looks like they solved this problem using the following shim:

    /* rAF shim. Gist: https://gist.github.com/julianshapiro/9497513 */
    var rAFShim = (function() {
        var timeLast = 0;

        return window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || function(callback) {
            var timeCurrent = (new Date()).getTime(),
                timeDelta;

            /* Dynamically set delay on a per-tick basis to match 60fps. */
            /* Technique by Erik Moller. MIT license: https://gist.github.com/paulirish/1579671 */
            timeDelta = Math.max(0, 16 - (timeCurrent - timeLast));
            timeLast = timeCurrent + timeDelta;

            return setTimeout(function() { callback(timeCurrent + timeDelta); }, timeDelta);
        };
    })();

Would it make sense to incorporate the same technique in velocity-react? Sadly, for our current project we still need to support IE 9 (for the time being).

**Comment by phopkins** [comment]
Seems reasonable. Could you make a PR?

We don't need to do the timing bits; `velocity-react` just wants to get to
the next tick of the event loop.

**Comment by RandScullard** [comment]
By "get to the next tick of the event loop", do you mean just do a setTimeout of zero?

**Comment by phopkins** [comment]
Yeah, if rAF isn't available that's fine for us. velocity-react doesn't
call rAF repeatedly, so the particular rate of call isn't important.
