### ISSUE TITLE
How to scroll based on property of wrapped component

### ISSUE THREAD

**Issue by stheobald** [twitter-fabric/velocity-react#68]
I'm trying to reason my way around getting an element to 'scroll' when a property changes. I have  this.props.active, and when this changes to true, the element should scroll.

I had anticipated doing something like:
```javascript
componentDidUpdate() {
  if (this.props.active) { 
    ReactDOM.findDOMNode(this).velocity('scroll', {duration: 500, offset: '54px'});
    // This works --> ReactDOM.findDOMNode(this).scrollIntoView({behavior: 'smooth'});
  }
}
```
But I haven't managed to get velocity to work in that context (window is not defined).
scrollIntoView works, but we can do much better/nicer/better supported things with velocity.

Is there a way to solve this scenario using velocity-react?

**Comment by phopkins** [comment]
I haven't tried it, but it's likely to work, since `velocity-react` just calls Velocity on child DOM nodes.

You may or may not want `runOnMount` to be true, depending upon how you want the “animation” to be triggered.

**Comment by stheobald** [comment]
I still couldn't see a way to trigger the animation based on a property with VelocityComponent. 
So I required the shim: `const velocity = require('velocity-react/lib/velocity-animate-shim');`
and did exactly as I outlined above.

**Comment by phopkins** [comment]
You'll want to add a `ref` to the component so you can access it, and call `runAnimation` on it when you want it to fire off.
