### ISSUE TITLE
Enter style not applied

### ISSUE THREAD

**Issue by mxstbr** [twitter-fabric/velocity-react#69]
I've got this setup:

```JSX
<VelocityTransitionGroup
  enter={{
    animation: {
      translateX: 0
    },
    style: {
      transform: 'translateX(-' + this.props.width + 'px)'
    }
  }}

  leave={{
    animation: {
      translateX: this.props.width + 'px'
    },
    style: {
      transform: 'translateX(0)'
    }
  }}

  runOnMount>
  {this.props.visible ? (
    <Wrapper>
      <img src={this.props.src} />
      { this.props.children }
    </Wrapper>
  ) : undefined }
</VelocityTransitionGroup>
```

Imagine multiple of those components next to each other. On enter, the `Wrapper` should slide in from the left, and the leaving `Wrapper` should slide out to the right.

The leave animation is working fine, but the `style` of the `enter` animation isn't applied before the animation starts, so it slides in from the right. Anybody know how to fix this?

**Comment by phopkins** [comment]
Try `translateX` as the key to the `style` block. velocity-react uses Velocity's style setting for consistency, not React's.

**Comment by mxstbr** [comment]
@phopkins you are a genious. That works, thanks!
