### ISSUE TITLE
Animation not firing properly

### ISSUE THREAD

**Issue by ffxsam** [twitter-fabric/velocity-react#70]
I'm probably using this wrong, but I'm trying to make an overly fade when a variable (`post`) is defined.

```
    return <div>
      {post ?
        <VelocityComponent animation={{opacity: post ? 1 : 0}} duration={300} runOnMount>
          <div style={{
            background: 'white',
            position: 'fixed',
            top: 0, right: 0, bottom: 0, left: 0, zIndex: 2000
          }}></div>
        </VelocityComponent> : ''
      }
    </div>
```

How can I achieve the effect I want? I obviously can't render the `<VelocityComponent>` and its children unless `post` is defined, otherwise there will be a transparent overlay blocking user interaction.

**Comment by phopkins** [comment]
You’ll need the component to stay in the DOM for the duration of the animation for the effect to appear. Two options come to mind:

* Keep using `VelocityComponent`, rendered all of the time, but use Velocity’s [display property](http://julian.com/research/velocity/#displayAndVisibility) (not in `animation`, but as its own `prop`) to get the element to display block/none at the beginning/end of the animation as necessary.

* Use `VelocityTransitionGroup` and have the white overlay as a child that’s added/removed from it. `VelocityTransitionGroup` will keep the child in the DOM while the animation runs, even if you’re no longer rendering it, and remove it when the animation is over.
