### ISSUE TITLE
finishAll uncaught error

### ISSUE THREAD

**Issue by zenonn37** [twitter-fabric/velocity-react#75]
Hi, I am getting this error using velocity 1.2.3,
Uncaught (in promise) Error: Velocity: First argument (finishAll) was not a property map, a known action, or a registered redirect. Aborting.(…).
Any ideas?
Thanks Chris

**Comment by phopkins** [comment]
Double-check that all versions of Velocity you have installed are 1.2.3? (Perhaps with `npm dedupe` as well.)

**Comment by zenonn37** [comment]
Thanks, I had two installed!
