### ISSUE TITLE
Animating a Show More option for a list

### ISSUE THREAD

**Issue by tomRedox** [twitter-fabric/velocity-react#76]
I have a list component that shows 3 records to start, and when a user presses the Show More button the list is re-rendered with 6 records.  I'm trying to animate between those two states, I thought I would be able to do something like this: 

```
   render() {
        console.log("OrdersListWrapper.render() ")
        
        let recordsToShow = 3;
        if (this.state.expanded) {
            recordsToShow = 6;
        }

        // Get tasks from this.data.tasks
        return (

            <div>
                <VelocityTransitionGroup component="div"
                                         enter={{animation: 'slideIn', duration: this.state.duration, style: {height: ''}}}
                                         leave={{animation: 'slideOut', duration: this.state.duration}}
                >
                        <div><OrdersList recordsToShow={recordsToShow}/></div>
                </VelocityTransitionGroup>
                {this.renderDeviceToggle()}
            </div>
        );
    }
```
But the animation does not work, it just jumps from showing 3 to 6 rows with no animation.  I don't understand why that's the case?

I can get it to work if I do the following: 

```
        return (

            <div>
                <VelocityTransitionGroup component="div"
                                         enter={{animation: 'slideIn', duration: this.state.duration, style: {height: ''}}}
                                         leave={{animation: 'slideOut', duration: this.state.duration}}
                >
                    {this.state.expanded ? undefined : <div><OrdersList recordsToShow={recordsToShow}/></div> }
                    {this.state.expanded ? <div><OrdersList recordsToShow={recordsToShow}/></div> : undefined }
                </VelocityTransitionGroup>
                {this.renderDeviceToggle()}
            </div>
        );
```

But the problem with that is that I am now rendering the OrdersList component twice, and that means it is hitting the database twice which I'd like to avoid.  

Can anyone help me understand what I need to do?

**Comment by phopkins** [comment]
I think the problem is the `<div>` around your `OrdersList` and the `OrdersList` itself. `ReactTransitionGroup` — and therefore `VelocityTransitionGroup` — operates only on direct children. You will need the components you’re adding / removing to be direct children of a `VelocityTransitionGroup` to animate them.

**Comment by tomRedox** [comment]
Hi @phopkins, thanks for the info. I got to the bottom of the issue, it was to do with Meteor; it causes a double render (one when the data is subscribed to and and another when the data actually gets to the client).  That meant that the actual render order was old state -> nothing -> new state, rather than old state -> new state which I think was stopping the animation working.  Splitting the component into a sub-component with a shouldComponentUpdate override that stops it rendering during the nothing phase got things working.
