### ISSUE TITLE
Update lodash version

### ISSUE THREAD

**Issue by jairj** [twitter-fabric/velocity-react#77]
Since version 4.x methods have moved up one level.
I'm getting a `Cannot find module "lodash/lang/isEqual"`.
In lodash 4.x this method is at "lodash/isEqual".

**Comment by phopkins** [comment]
Not sure what the error is… we're pegged to the 3.10 implementation.

**Comment by TCMiranda** [comment]
It seems that the only problem is the "namespace" isn't it?
From: `lodash/lang/isEqual`
To: `lodash/isEqual`

Pluck has been deprecated also, will it be hard to upgrade?

**Comment by phopkins** [comment]
Presumably we could upgrade to 4, though I don't see why you'd be getting an error now. In my tests, NPM installed lodash 3.10 into velocity-react's node_modules folder.

You may need to wipe your node_modules directory and do a re-install to get that, though.

**Comment by jairj** [comment]
Yeah you're right..
I got the error when upgraded the package. 
Reinstalling velocity-react will solve it..

Thanks!

**Comment by axelson** [comment]
+1 to this so that I don't need an extra copy of lodash in my distributed bundle

**Comment by luisherranz** [comment]
> +1 to this so that I don't need an extra copy of lodash in my distributed bundle

True!

**Comment by finneganh** [comment]
Note that velocity-react doesn't require all of lodash, just a handful of functions. So, you're not getting a full extra copy in your bundle.

**Comment by eddiemonge** [comment]
Then why not only require the lodash packages you are using?

**Comment by finneganh** [comment]
The components that use lodash are already only requiring/importing the
particular methods that they need.

**Comment by eddiemonge** [comment]
Not really. All of lodash is still included. This only installs the ones that are actually used: https://github.com/twitter-fabric/velocity-react/pull/219

**Comment by finneganh** [comment]
My understanding is that a bundler such as webpack is only going to pull in
the directly-required files (and their transitive dependencies), regardless
of what's in node_modules, so I don't know what that PR gains.

**Comment by eddiemonge** [comment]
It gains not having to install all of lodash since its a dependency and gets installed when this does. Its not only about the production environment but also dev. Faster installs, less file size overhead. Why not be explicit?

**Comment by anyab5** [comment]
@finneganh 
the package.json of react velocity includes lodash 3.10.1 or above.
"lodash": "^3.10.1",

So basically anyone who already upgraded lodash to ^4.0.0 in their projects will have the more updated version of lodash and the 3.10 will not be install for react-velocity.

This result in having breaking changes for the current code using lodash in react-velocity that is not compatible with the newer lodash and thus unfortunately not usable as is (without forking)

It would be great if you could consider upgrading to newer version or accept the pull request that already does it #219

**Comment by SterlingVix** [comment]
@finneganh -- I'm also having this Lodash issue, though I'm not 100% confident that it's velocity-react (50/50 chance at this point). But regarding the explicit imports in Lodash and webpack only requiring the necessary modules -- I don't think you get that for free with Webpack.

My understanding is that if you were to import all of your lodash statements namespaced, i.e.:

`import { merge } from 'lodash';`

... then Webpack would, as part of optimizing the dependency graph, only create a module out of `merge`.

But if you import all of lodash, i.e.:

`import _ from 'lodash';`

... then you've got all of lodash coming your way.

You can validate the weight of lodash in velocity-react using the `bundle-analyzer-tool`:

https://github.com/th0r/webpack-bundle-analyzer

**Comment by finneganh** [comment]
Are you doing some top-level aliasing shenanigans with webpack? If npm is
well-behaved, it will put lodash in a node_modules directory relative to
velocity-react, and that's what the velocity-react package will import.

The velocity-react imports are already directly to lodash files, so it
doesn't rely on tree-shaking or anything along those lines.
