### ISSUE TITLE
svg move animation

### ISSUE THREAD

**Issue by pavel1860** [twitter-fabric/velocity-react#78]
hi.
I need to create svg animation. I have two rectangles wraped in g component and all of them are in a react class (see the code) when I use VelocityComponent on the obj class some of the animations working, like the opacity , translateX and the fill animation but not the move X animation.

`
class Obj extends React.Component{

    render(){
        return(
            <g>
                <rect x={100} y={300} width={200} height={200}/>
                <rect x={400} y={300} width={100} height={100}/>
            </g>
        );
    }
}

export default class MainVelocity extends React.Component {

    constructor() {
        super();
        this.state = {showSubComponent:false};
    }

    onClick(){
        this.setState({showSubComponent: !this.state.showSubComponent});
    }

    render() {
        var anim = { opacity: this.state.showSubComponent ? 1 : 0 ,
            x:this.state.showSubComponent?"+=300":"-=300",
            translateX:300,
            fillGreen:this.state.showSubComponent?255:0,
           }
        return (
            <div>
                <button onClick={this.onClick.bind(this)}>click me</button>
                <svg
                    width={window.innerWidth}
                    height={window.innerHeight}
                >
                        <VelocityComponent animation={anim} duration={500}>
                            <Obj/>
                        </VelocityComponent>
                </svg>
            </div>
        );
    }
}
`

I could not find any tutorials on how to create svg animations with velocity-react. is it possible? and how is the library support for svg?
by the way I think the way you  integrated velocity into react is great!
thanks.

**Comment by phopkins** [comment]
Check and see if the [Velocity docs on SVG](http://julian.com/research/velocity/#svg) have the info you need.
