### ISSUE TITLE
scrollTop

### ISSUE THREAD

**Issue by jolic** [twitter-fabric/velocity-react#83]
How can I use the scrollTop with velocity-react like described here: http://julian.com/research/velocity/#scroll ?

Any hints?

**Comment by jolic** [comment]
Figured out...

**Comment by JoshWhite** [comment]
Hi @jolic - could you post your solution? I'm struggling to figure this out!

**Comment by jordan-enev** [comment]
Hello guys,

I've answered on the above post and created a demo [here](https://github.com/jordan-enev/react-velocity-scroll).
