### ISSUE TITLE
on item leave it's jumping to the end of the list and not holding position

### ISSUE THREAD

**Issue by antsav** [twitter-fabric/velocity-react#84]
VelocityTransitionGroup:
on item leave, animation starts and item is moved to the bottom of the list. 
It's not holding position in the middle of the list until animation is complete.

here is the example of correct custom made behaviour and animation [http://codepen.io/makenosound/pen/rstvx](http://codepen.io/makenosound/pen/rstvx)
item is staying in the middle of the list till the end of the animation

**Comment by finneganh** [comment]
For debugging animation issues, I recommend turning down the animation time to something on the order of 60s. That should give you enough time to investigate what's going on in a web inspector. The React `TransitionGroup` code should be keeping DOM elements in the correct order, providing your `key` attributes aren’t changing, so I would suspect there’s either something with keys or with your animation.

**Comment by antsav** [comment]
same problem is visible here : http://codepen.io/agrewell/pen/ZYdGOJ

**Comment by antsav** [comment]
resolved )

found out that I was having key as index of iteration and reinjected element had conflicted key

Like below: 
```
let index = 0;
[...].map((item)=>{
  index ++;
  <div key={index}>
})
```

changed to unique key and everything works perfect!

**Comment by finneganh** [comment]
Glad to hear!
