### ISSUE TITLE
Problems with VelocityTransitionGroup on react-templates

### ISSUE THREAD

**Issue by sergio11** [twitter-fabric/velocity-react#85]
Hi,

I get the next error to use VelocityTransistionGroup in a react-template

`
Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`

This is the code of the template:

```
<rt-require dependency="react-bootstrap/lib/Grid" as="Grid" />
<rt-require dependency="react-bootstrap/lib/Row" as="Row" />
<rt-require dependency="react-bootstrap/lib/ListGroup" as="ListGroup"/>
<rt-require dependency="react-bootstrap/lib/ListGroupItem" as="ListGroupItem"/>
<rt-require dependency="react-loader" as="Loader" />
<rt-require dependency="velocity-react/velocity-transition-group" as="VelocityTransitionGroup" />

<VelocityTransitionGroup component="div" enter="transition.fadeIn" leave="transition.fadeOut" duration={200}>
    <Grid>
        <Row>
                <Loader loaded="{this.state.loaded}" color='#bf5a16' top="50%" left="50%" scale={1.00} width={10}>
                    <ListGroup>
                        <ListGroupItem rt-repeat="conversation in this.state.conversations" key='{conversationIndex}' header="{conversation.title}">Tiene {conversation.messages ? conversation.messages.length : 0 } mensajes </ListGroupItem>
                    </ListGroup>
                </Loader>
        </Row>
   </Grid>
</ VelocityTransitionGroup>
```
In this way I have the render method:
```
import Template from './Conversations.rt.js'
render(){
        return Template.call(this);
 }
```
Thanks and greetings

**Comment by finneganh** [comment]
Sounds like this may be something on the React Template side? `VelocityTransitionGroup` does not use refs itself. You could see if you get the same problem using React’s `TransitionGroup`, which is what VTG delegates to.

**Comment by clementoriol** [comment]
Adding my two cents, got the same issue, without using react-template. It was related to velocity-react (or one of its dependencies) pulling a different version than the one I had in the project. 
Like stated in the react error message, two versions of React were running, causing issues (https://gist.github.com/jimfb/4faa6cbfb1ef476bd105).

I managed to make sure both my project and velocity-react were depending on the same react version, and it fixed the issue.
Shrinkwrapping your dependencies afterwards should help to make sure this issue doesn't arise again.
