### ISSUE TITLE
RegisterEffect reset property support

### ISSUE THREAD

**Issue by dcalhoun** [twitter-fabric/velocity-react#87]
Does velocity-react support the `reset` property for [`Velocity.RegisterEffect`](http://julian.com/research/velocity/#uiPack)?

Specifically, I'm attempting to "clean up" the style attribute of a component after the animation is complete.

```javascript
// Define prep styles for animation
var prepStyles = {
  bottom: 0,
  left: 0,
  position: 'absolute',
  right: 0,
  top: 0
}

var resetStyles = {
  bottom: 'auto',
  left: 'auto',
  position: 'static',
  right: 'auto',
  top: 'auto',
}

// Register effects
var scaleFadeIn = velocityHelpers.registerEffect({
  defaultDuration: 600,
  calls: [
    [{
      opacity: [1, 0],
      scale: [1, [500, 30], 0.5]
    }]
  ],
  reset: resetStyles
})

var scaleFadeOut = velocityHelpers.registerEffect({
  defaultDuration: 600,
  calls: [
    [{
      opacity: [0, 1],
      scale: [0.5, [500, 30], 1]
    }]
  ],
  reset: resetStyles
})

// Use animation with style hash
<VelocityTransitionGroup
  enter={{ animation: scaleFadeIn, style: prepStyles }}
  leave={{ animation: scaleFadeOut, style: prepStyles }}>
  {this.state.first ? <First /> : undefined}
  {!this.state.first ? <Second /> : undefined}
</VelocityTransitionGroup>
```

**Comment by finneganh** [comment]
Hrm. Unsure. VelocityTransitionGroup sets a complete handler, but I don't
know exactly how that interacts with the complete handler that UI Pack
adds. You'd need to do some debugger tracing to see how that plays out. I
wouldn't expect VelocityTransitionGroup to behave any differently from any
call to "animate" that has its own complete handler.

Theoretically you could reset the styles with a complete handler passed to
VelocityTransitionGroup, though it looks like it currently eats the
arguments / this that would make that possible.

Updating VelocityTransitionGroup to pass the args from its complete handler
into optsCompleteFn (and probably call it with the right "this") would fix
that, if you want to make a PR.

**Comment by dcalhoun** [comment]
Thank you for implementing support with the `complete` callback.

Just to follow up, it appears the `reset` property of `Velocity.RegisterEffect` _is_ working within velocity-react. It turns out my issue is that [Velocity does not accept non-integer values](https://github.com/julianshapiro/velocity/issues/366#issuecomment-64450918).
