### ISSUE TITLE
React 15 - remove peerDependencies 

### ISSUE THREAD

**Issue by davidspiess** [twitter-fabric/velocity-react#89]
Hey, would you mind removing peerDependencies so we can choose the appropriate react version ourselves? Many libraries turned their backs to peerDependencies now.

**Comment by unboundfire** [comment]
👍

**Comment by finneganh** [comment]
I'm not 100% sure that's feasible given the hard dependency on `velocity-addons-transition-group`, which has its own `peerDependency` on `react`.

Regardless, testing an update tonight w/ React 15 supported.
