### ISSUE TITLE
1.1.4 -> 1.1.5 is a breaking change

### ISSUE THREAD

**Issue by rtsao** [twitter-fabric/velocity-react#95]
`velocity-react` has a `react-addons-transition-group` dependency, which in turn has a **strict** React peerDependency. For example:

In `react-addons-transiton-group@15`:
```
"peerDependencies": {
    "react": "^15.0.1"
  },
```

In `react-addons-transition-group@0.14`:
```
  "peerDependencies": {
    "react": "^0.14.8"
  },
```

The problem is in the `velocity-react` package.json:
```
  "dependencies": {
    "react-addons-transition-group": "^0.14.0 || ^15.0.0",
  },
```

I think this will always pull down `react-addons-transition-group@15`, even in a React 0.14 application, which results in an unmet peerDependency.

**Reproduction steps:**
```
npm i react@0.14 react-dom@0.14 --save
npm i velocity-react@1.1.5 --save
cat ./node_modules/react-addons-transition-group/package.json | grep peerDependencies -A 1
```
Should yield:
```
  "peerDependencies": {
    "react": "^15.0.1"
```

This means `velocity-react@1.1.5` cannot be used with React 0.14 and is thus a breaking change.

**Comment by finneganh** [comment]
You may need to specify `react-addons-transition-group` at 0.14.x in your dependencies.

Sorry for the headaches around this; for some reason this React upgrade isn't going as smoothly as 0.13 -> 0.14.

I think one lesson is to always make sure you're shrinkwrapping your dependencies so this doesn't bite arbitrarily.
