### ISSUE TITLE
CSS reset breaks animation

### ISSUE THREAD

**Issue by madshargreave** [twitter-fabric/velocity-react#96]
Hi

I use https://github.com/premasagar/cleanslate CSS reset on a JS widget to avoid style leaking in/out of my widget.

This however breaks all movement on animations.

Any way around this?

**Comment by finneganh** [comment]
For debugging stuff like this, I usually recommend slowing the animation down to 30s or so you have enough time to look in the web inspector to see how styles are cascading or conflicting.

This may be an issue you'd need to address with Velocity to allow for animation styles that override `!important` CSS.
