### ISSUE TITLE
Is it possible to run animation Sequence in parallel?

### ISSUE THREAD

**Issue by axelson** [twitter-fabric/velocity-react#97]
`$.Velocity.RunSequence()` supports setting `sequenceQueue: false` to allow animations to run in parallel? I don't see a way to accomplish this with the library. Is there a list of unsupported features anywhere?

Velocity docs: http://julian.com/research/velocity/#uiPack

**Comment by finneganh** [comment]
I haven’t looked closely at that, as I'm not sure how it would fit in with the declarative approach to animations. Feel free to discuss if you have a feeling of how it would integrate.

**Comment by axelson** [comment]
Yeah, that's about what I figured. I think simultaneous animations will be non-trivial to integrate into a declarative approach.
